/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newstone_soriwa_Soriwa */

#ifndef _Included_com_newstone_soriwa_Soriwa
#define _Included_com_newstone_soriwa_Soriwa
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_newstone_soriwa_Soriwa
 * Method:    getString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_newstone_soriwa_Soriwa_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
