/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_newstone_soriwa_Soriwa */
#include "include/com_newstone_soriwa_Soriwa.h"

#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_newstone_soriwa_Soriwa_getString(JNIEnv *env, jobject obj) {

}

#ifdef __cplusplus
}
#endif